services:
  postgres:
    container_name: asso-saas-postgres
    image: postgres:16-alpine
    ports:
      - 5544:5432
    volumes:
      - ~/apps/asso-saas-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=asso_saas
      - POSTGRES_USER=asso_saas
      - POSTGRES_DB=asso_saas
